"""
Model Comparison Report - Complete
==================================

Generates a model comparison report comparing different panel data models.
"""

from pathlib import Path

import numpy as np
import pandas as pd

# Import PanelBox components
import panelbox as pb
from panelbox.report.report_manager import ReportManager

# Set random seed for reproducibility
np.random.seed(42)


def create_panel_data():
    """Create panel data."""
    print("Creating panel data...")

    n_firms = 50
    n_years = 10
    n_obs = n_firms * n_years

    # Create panel structure
    data = pd.DataFrame(
        {
            "firm": np.repeat(range(1, n_firms + 1), n_years),
            "year": np.tile(range(2010, 2010 + n_years), n_firms),
        }
    )

    # Add firm-specific fixed effects
    firm_effect = {i: np.random.normal(0, 5) for i in range(1, n_firms + 1)}
    data["firm_effect"] = data["firm"].map(firm_effect)

    # Generate regressors
    data["capital"] = np.random.uniform(100, 1000, n_obs)
    data["labor"] = np.random.uniform(50, 500, n_obs)

    # Generate errors
    errors = np.random.normal(0, 10, n_obs)

    # Generate dependent variable
    data["output"] = 10 + data["firm_effect"] + 0.5 * data["capital"] + 0.3 * data["labor"] + errors
    data = data.drop("firm_effect", axis=1)

    print(f"  ✅ Created panel: {n_firms} firms, {n_years} years")
    return data


def prepare_comparison_data(pooled_results, fe_results, re_results):
    """Prepare model comparison data for report."""
    print("Preparing model comparison data...")

    # Model summaries
    models = [
        {
            "name": "Pooled OLS",
            "type": "Pooled OLS",
            "r_squared": float(pooled_results.rsquared),
            "r_squared_formatted": f"{pooled_results.rsquared:.4f}",
            "aic": float(pooled_results.aic) if hasattr(pooled_results, "aic") else None,
            "bic": float(pooled_results.bic) if hasattr(pooled_results, "bic") else None,
            "nobs": int(pooled_results.nobs),
            "nobs_formatted": f"{pooled_results.nobs:,}",
        },
        {
            "name": "Fixed Effects",
            "type": "Fixed Effects",
            "r_squared": float(fe_results.rsquared),
            "r_squared_formatted": f"{fe_results.rsquared:.4f}",
            "aic": float(fe_results.aic) if hasattr(fe_results, "aic") else None,
            "bic": float(fe_results.bic) if hasattr(fe_results, "bic") else None,
            "nobs": int(fe_results.nobs),
            "nobs_formatted": f"{fe_results.nobs:,}",
        },
        {
            "name": "Random Effects",
            "type": "Random Effects",
            "r_squared": float(re_results.rsquared),
            "r_squared_formatted": f"{re_results.rsquared:.4f}",
            "aic": float(re_results.aic) if hasattr(re_results, "aic") else None,
            "bic": float(re_results.bic) if hasattr(re_results, "bic") else None,
            "nobs": int(re_results.nobs),
            "nobs_formatted": f"{re_results.nobs:,}",
        },
    ]

    # Summary comparison
    summary = {
        "total_models": 3,
        "best_model": "Fixed Effects",  # Based on R-squared
        "best_r_squared": float(fe_results.rsquared),
        "best_r_squared_formatted": f"{fe_results.rsquared:.4f}",
    }

    # Coefficient comparison
    coefficients = []
    for var in ["capital", "labor"]:
        coef_data = {
            "variable": var,
            "pooled_coef": float(pooled_results.params.get(var, 0)),
            "pooled_se": float(pooled_results.std_errors.get(var, 0)),
            "fe_coef": float(fe_results.params.get(var, 0)),
            "fe_se": float(fe_results.std_errors.get(var, 0)),
            "re_coef": float(re_results.params.get(var, 0)),
            "re_se": float(re_results.std_errors.get(var, 0)),
        }
        coefficients.append(coef_data)

    # Model info
    model_info = {
        "formula": "output ~ capital + labor",
        "n_models": 3,
        "estimators": ["Pooled OLS", "Fixed Effects", "Random Effects"],
    }

    print(f"  ✅ Comparison data prepared")

    return {
        "report_title": "Model Comparison Report",
        "summary": summary,
        "model_info": model_info,
        "models": models,
        "coefficients": coefficients,
        "charts": None,  # Charts would be generated by visualization system
    }


def main():
    print("=" * 80)
    print("MODEL COMPARISON REPORT - FULL")
    print("=" * 80)
    print()

    # 1. Create panel data
    data = create_panel_data()
    print()

    # 2. Estimate multiple models
    print("Estimating models...")

    # Pooled OLS
    pooled = pb.PooledOLS("output ~ capital + labor", data, "firm", "year")
    pooled_results = pooled.fit()
    print(f"  ✅ Pooled OLS estimated")

    # Fixed Effects
    fe = pb.FixedEffects("output ~ capital + labor", data, "firm", "year")
    fe_results = fe.fit(cov_type="clustered")
    print(f"  ✅ Fixed Effects estimated")

    # Random Effects
    re = pb.RandomEffects("output ~ capital + labor", data, "firm", "year")
    re_results = re.fit()
    print(f"  ✅ Random Effects estimated")
    print()

    # 3. Prepare comparison data
    report_data = prepare_comparison_data(pooled_results, fe_results, re_results)
    print()

    # 4. Generate HTML report
    print("Generating HTML report...")
    report_mgr = ReportManager(enable_cache=True, minify=False)

    try:
        html = report_mgr.generate_report(
            report_type="comparison",
            template="comparison/interactive/index.html",
            context=report_data,
            embed_assets=True,
            include_plotly=True,
        )

        print(f"  ✅ Report generated: {len(html):,} characters")
        print()

        # 5. Save report
        print("Saving report...")
        output_path = Path("/home/guhaase/projetos/panelbox/model_comparison_report.html")
        output_path.write_text(html, encoding="utf-8")
        file_size_kb = output_path.stat().st_size / 1024

        print(f"  ✅ Report saved: {output_path}")
        print(f"  ✅ File size: {file_size_kb:.1f} KB")
        print()

        # 6. Summary
        print("=" * 80)
        print("✅ MODEL COMPARISON REPORT GENERATED SUCCESSFULLY")
        print("=" * 80)
        print()
        print("Report Details:")
        print(f"  • Total models: {report_data['summary']['total_models']}")
        print(f"  • Best model: {report_data['summary']['best_model']}")
        print(f"  • Best R-squared: {report_data['summary']['best_r_squared_formatted']}")
        print(f"  • Estimators: {', '.join(report_data['model_info']['estimators'])}")
        print()
        print(f"Open the report: {output_path}")
        print("=" * 80)

    except Exception as e:
        print(f"  ❌ Error generating report: {e}")
        import traceback

        traceback.print_exc()


if __name__ == "__main__":
    main()
