"""
Validation tests for stability/eigenvalues against R implementation.

This test suite compares PanelBox's stability analysis with R's eigenvalue
calculation for the companion matrix.
"""

import json
import subprocess
import tempfile
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from panelbox.var import PanelVAR, PanelVARData

pytestmark = pytest.mark.r_validation


@pytest.fixture(scope="module")
def r_stability_results():
    """
    Run R stability script and return results.

    Returns
    -------
    dict
        Dictionary containing R stability results including:
        - eigenvalues: dict with real and imaginary parts
        - eigenvalue_moduli: array of eigenvalue moduli
        - max_modulus: maximum eigenvalue modulus
        - is_stable: whether system is stable
        - stability_margin: 1 - max_modulus
        - companion_matrix: companion matrix
    """
    # Path to R script
    script_path = Path(__file__).parent / "test_vs_r_stability.R"

    # Run R script
    result = subprocess.run(
        ["Rscript", str(script_path)], capture_output=True, text=True, timeout=60
    )

    if result.returncode != 0:
        pytest.skip(f"R script failed: {result.stderr}")

    # Load results
    results_path = Path(tempfile.gettempdir()) / "pvar_stability_results.json"
    if not results_path.exists():
        pytest.skip("R stability results file not found")

    with open(results_path) as f:
        r_results = json.load(f)

    return r_results


@pytest.fixture(scope="module")
def python_stability_results(r_stability_results):
    """
    Estimate Panel VAR using PanelBox with the same data as R.

    Parameters
    ----------
    r_stability_results : dict
        R stability results (triggers R script execution)

    Returns
    -------
    PanelVARResult
        Estimation results from PanelBox
    """
    # Load data generated by R
    data_path = Path(tempfile.gettempdir()) / "pvar_stability_data.csv"
    if not data_path.exists():
        pytest.skip("R stability data not found")

    df = pd.read_csv(data_path)

    # Create PanelVARData
    pvar_data = PanelVARData(
        data=df,
        endog_vars=["y1", "y2", "y3"],
        entity_col="entity",
        time_col="time",
        lags=2,
        trend="none",
    )

    # Estimate
    model = PanelVAR(pvar_data)
    result = model.fit(method="ols", cov_type="nonrobust")

    return result


class TestStabilityVsR:
    """Test suite for stability validation against R."""

    def test_companion_matrix_close(self, python_stability_results, r_stability_results):
        """
        Test that companion matrix matches R results.

        This is a fundamental test - if the companion matrix matches,
        the eigenvalues should also match.
        """
        # Get Python companion matrix
        companion_py = python_stability_results.companion_matrix()

        # Get R companion matrix
        companion_r = np.array(r_stability_results["companion_matrix"])

        # Compare
        np.testing.assert_allclose(
            companion_py,
            companion_r,
            rtol=1e-6,
            atol=1e-6,
            err_msg="Companion matrix does not match R implementation",
        )

    def test_eigenvalues_close(self, python_stability_results, r_stability_results):
        """
        Test that eigenvalues match R results within tolerance.

        Note: Eigenvalues may appear in different order, so we sort by modulus.
        Complex conjugate pairs may also have opposite signs, so we compare
        absolute values of imaginary parts.
        """
        # Get Python eigenvalues
        eigs_py = python_stability_results.eigenvalues

        # Get R eigenvalues (reconstruct complex numbers)
        eigs_r_real = np.array(r_stability_results["eigenvalues"]["real"])
        eigs_r_imag = np.array(r_stability_results["eigenvalues"]["imag"])
        eigs_r = eigs_r_real + 1j * eigs_r_imag

        # Sort both by modulus (eigenvalues may appear in different order)
        eigs_py_sorted = eigs_py[np.argsort(np.abs(eigs_py))]
        eigs_r_sorted = eigs_r[np.argsort(np.abs(eigs_r))]

        # Compare real parts
        np.testing.assert_allclose(
            np.real(eigs_py_sorted),
            np.real(eigs_r_sorted),
            rtol=1e-6,
            atol=1e-6,
            err_msg="Eigenvalue real parts do not match R implementation",
        )

        # Compare absolute values of imaginary parts (sign may differ for conjugate pairs)
        np.testing.assert_allclose(
            np.abs(np.imag(eigs_py_sorted)),
            np.abs(np.imag(eigs_r_sorted)),
            rtol=1e-6,
            atol=1e-6,
            err_msg="Eigenvalue imaginary parts moduli do not match R implementation",
        )

    def test_eigenvalue_moduli_close(self, python_stability_results, r_stability_results):
        """
        Test that eigenvalue moduli match R results.

        This is a critical test for stability assessment.
        """
        # Get Python eigenvalue moduli (sorted)
        eigs_py = python_stability_results.eigenvalues
        moduli_py = np.sort(np.abs(eigs_py))

        # Get R eigenvalue moduli (sorted)
        moduli_r = np.sort(r_stability_results["eigenvalue_moduli"])

        # Compare
        np.testing.assert_allclose(
            moduli_py,
            moduli_r,
            rtol=1e-6,
            atol=1e-6,
            err_msg="Eigenvalue moduli do not match R implementation",
        )

    def test_max_modulus_close(self, python_stability_results, r_stability_results):
        """
        Test that maximum eigenvalue modulus matches R results.

        This is the key metric for stability.
        """
        # Get Python max modulus
        max_mod_py = python_stability_results.max_eigenvalue_modulus

        # Get R max modulus
        max_mod_r = r_stability_results["max_modulus"]

        # Compare
        np.testing.assert_allclose(
            max_mod_py,
            max_mod_r,
            rtol=1e-6,
            atol=1e-6,
            err_msg="Max eigenvalue modulus does not match R implementation",
        )

    def test_stability_status_matches(self, python_stability_results, r_stability_results):
        """
        Test that stability status (stable/unstable) matches R.
        """
        # Get Python stability status
        is_stable_py = python_stability_results.is_stable()

        # Get R stability status
        is_stable_r = r_stability_results["is_stable"]

        # Compare
        assert is_stable_py == is_stable_r, (
            f"Stability status mismatch: Python={is_stable_py}, R={is_stable_r}"
        )

    def test_stability_margin_close(self, python_stability_results, r_stability_results):
        """
        Test that stability margin matches R results.

        Stability margin = 1 - max_eigenvalue_modulus
        """
        # Get Python stability margin
        margin_py = python_stability_results.stability_margin

        # Get R stability margin
        margin_r = r_stability_results["stability_margin"]

        # Compare
        np.testing.assert_allclose(
            margin_py,
            margin_r,
            rtol=1e-6,
            atol=1e-6,
            err_msg="Stability margin does not match R implementation",
        )

    def test_coefficient_matrices_match(self, python_stability_results, r_stability_results):
        """
        Test that coefficient matrices A1 and A2 match R results.

        This validates that the estimation is correct, which is necessary
        for eigenvalues to be meaningful.
        """
        # Get Python coefficient matrices
        A1_py = python_stability_results.A_matrices[0]
        A2_py = python_stability_results.A_matrices[1]

        # Get R coefficient matrices
        A1_r = np.array(r_stability_results["A1"])
        A2_r = np.array(r_stability_results["A2"])

        # Compare A1
        np.testing.assert_allclose(
            A1_py,
            A1_r,
            rtol=1e-6,
            atol=1e-6,
            err_msg="A1 coefficient matrix does not match R implementation",
        )

        # Compare A2
        np.testing.assert_allclose(
            A2_py,
            A2_r,
            rtol=1e-6,
            atol=1e-6,
            err_msg="A2 coefficient matrix does not match R implementation",
        )


if __name__ == "__main__":
    # Run tests
    pytest.main([__file__, "-v", "-s"])
