"""
Validation tests for Panel VECM rank selection against R implementation (urca package).

This test suite compares PanelBox's Panel VECM rank selection with R's urca package
Johansen cointegration test.

NOTE: urca::ca.jo is for time series (not panels). We validate the methodology by
comparing results for individual entities. Panel implementation extends this by
averaging across entities (Larsson et al. 2001).
"""

import json
import subprocess
import tempfile
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from panelbox.var import PanelVARData
from panelbox.var.vecm import CointegrationRankTest

pytestmark = pytest.mark.r_validation


@pytest.fixture(scope="module")
def r_validation_results():
    """
    Run R validation script for rank selection and return results.

    Returns
    -------
    dict
        Dictionary containing R Johansen test results including:
        - eigenvalues
        - trace_test: statistics, critical values, selected rank
        - maxeig_test: statistics, critical values, selected rank
    """
    # Path to R script
    script_path = Path(__file__).parent / "test_vecm_rank_vs_r.R"

    # Run R script
    result = subprocess.run(
        ["Rscript", str(script_path)], capture_output=True, text=True, timeout=120
    )

    if result.returncode != 0:
        pytest.skip(f"R script failed: {result.stderr}")

    # Print R output for debugging
    if result.stdout:
        print("\nR Output:")
        print(result.stdout)

    # Load results
    results_path = Path(tempfile.gettempdir()) / "vecm_rank_r_results.json"
    if not results_path.exists():
        pytest.skip("R results file not found")

    with open(results_path) as f:
        r_results = json.load(f)

    return r_results


@pytest.fixture(scope="module")
def panel_data():
    """
    Load panel data generated by R script.

    Returns
    -------
    pd.DataFrame
        Panel data with cointegrated variables
    """
    data_path = Path(tempfile.gettempdir()) / "vecm_rank_test_data.csv"
    if not data_path.exists():
        pytest.skip("R test data not found")

    df = pd.read_csv(data_path)
    return df


@pytest.fixture(scope="module")
def python_rank_results_entity1(panel_data):
    """
    Run rank test on first entity only (for comparison with R ca.jo).

    Parameters
    ----------
    panel_data : pd.DataFrame
        Full panel data

    Returns
    -------
    RankSelectionResult
        Rank selection results from PanelBox for entity 1
    """
    # Extract entity 1 only
    entity1_data = panel_data[panel_data["entity"] == 1].copy()

    # Create PanelVARData (treating as panel with N=1)
    pvar_data = PanelVARData(
        data=entity1_data,
        endog_vars=["y1", "y2", "y3"],
        entity_col="entity",
        time_col="time",
        lags=2,  # VECM(1) = VAR(2) in levels
        trend="none",
    )

    # Run rank test
    rank_test = CointegrationRankTest(pvar_data)
    results = rank_test.test_rank()

    return results


@pytest.fixture(scope="module")
def python_rank_results_full_panel(panel_data):
    """
    Run rank test on full panel (all entities).

    This is what users would actually do - test on the full panel.

    Parameters
    ----------
    panel_data : pd.DataFrame
        Full panel data

    Returns
    -------
    RankSelectionResult
        Rank selection results from PanelBox for full panel
    """
    # Create PanelVARData
    pvar_data = PanelVARData(
        data=panel_data,
        endog_vars=["y1", "y2", "y3"],
        entity_col="entity",
        time_col="time",
        lags=2,
        trend="none",
    )

    # Run rank test
    rank_test = CointegrationRankTest(pvar_data)
    results = rank_test.test_rank()

    return results


class TestVecmRankVsR:
    """Test suite for validation against R urca implementation."""

    def test_rank_selection_methodology(self, python_rank_results_entity1, r_validation_results):
        """
        Test that rank selection methodology is consistent with R.

        We cannot expect exact numerical match because:
        1. PanelBox uses panel-specific methods (Larsson et al. 2001)
        2. R urca uses time series Johansen test

        But we can verify:
        - Same number of variables (K)
        - Rank selection in plausible range [0, K-1]
        - Both identify cointegration (r > 0) for known cointegrated data
        """
        # Get R results (entity 1)
        r_rank_trace = r_validation_results["entity1"]["trace_test"]["selected_rank"]
        r_rank_maxeig = r_validation_results["entity1"]["maxeig_test"]["selected_rank"]

        # Get Python results (entity 1)
        py_rank = python_rank_results_entity1.selected_rank

        # Basic sanity checks
        assert py_rank >= 0, "Rank should be non-negative"
        assert py_rank < 3, "Rank should be less than K"

        # Both should detect cointegration (r > 0) for this DGP
        # This is a weak test but reasonable given methodology differences
        assert py_rank > 0 or r_rank_trace > 0 or r_rank_maxeig > 0, (
            "At least one method should detect cointegration in DGP with r=1"
        )

        print("\nRank selection comparison:")
        print(f"  R (trace):    {r_rank_trace}")
        print(f"  R (max-eig):  {r_rank_maxeig}")
        print(f"  Python:       {py_rank}")

    def test_eigenvalues_reasonable(self, python_rank_results_entity1, r_validation_results):
        """
        Test that eigenvalues are in reasonable range.

        Eigenvalues should be in [0, 1] for cointegration tests.
        """
        r_eigenvalues = np.array(r_validation_results["entity1"]["eigenvalues"])

        # R eigenvalues should all be in [0, 1]
        # Use tolerance for numerical precision (very small negative values OK)
        assert np.all(r_eigenvalues >= -1e-10), (
            "Eigenvalues should be non-negative (with numerical tolerance)"
        )
        assert np.all(r_eigenvalues <= 1), "Eigenvalues should be <= 1"

        # Eigenvalues should be sorted (descending)
        assert np.all(r_eigenvalues[:-1] >= r_eigenvalues[1:]), (
            "Eigenvalues should be sorted descending"
        )

        print(f"\nR Eigenvalues: {r_eigenvalues}")

    def test_full_panel_detects_cointegration(self, python_rank_results_full_panel):
        """
        Test that full panel rank test detects cointegration.

        For DGP with r=1 known cointegration, panel test should detect r > 0.
        """
        py_rank = python_rank_results_full_panel.selected_rank

        # Should detect cointegration
        assert py_rank > 0, "Panel test should detect cointegration (r > 0)"

        # Should not over-estimate rank
        assert py_rank < 3, "Rank should be less than K"

        print(f"\nFull panel rank selection: {py_rank}")
        print("Expected rank (DGP): 1")

        # Display summary
        print("\n" + "=" * 70)
        print(python_rank_results_full_panel.summary())
        print("=" * 70)

    def test_trace_and_maxeig_convergence(self, python_rank_results_full_panel):
        """
        Test that trace and max-eigenvalue tests give similar results.

        In most cases, both tests should converge to same rank selection.
        """
        results = python_rank_results_full_panel

        # Get selected ranks from both tests
        # (This assumes the implementation tracks both)
        # If not available, this test can be skipped

        # For now, just verify that the selected rank is consistent
        # across the combined decision
        assert results.selected_rank >= 0
        assert results.selected_rank < 3

        print(f"\nSelected rank (combined): {results.selected_rank}")

    def test_data_dimensions_match(self, panel_data, r_validation_results):
        """Test that data dimensions match between Python and R."""
        # R results
        r_N = r_validation_results["N"]
        r_T = r_validation_results["T"]
        r_K = r_validation_results["K"]

        # Python data
        py_N = panel_data["entity"].nunique()
        py_T = panel_data.groupby("entity").size().iloc[0]
        py_K = 3  # y1, y2, y3

        assert py_N == r_N, f"Number of entities mismatch: Python={py_N}, R={r_N}"
        assert py_T == r_T, f"Time periods mismatch: Python={py_T}, R={r_T}"
        assert py_K == r_K, f"Number of variables mismatch: Python={py_K}, R={r_K}"


class TestVecmRankTestOutput:
    """Test that rank test output and summary are properly formatted."""

    def test_summary_displays(self, python_rank_results_full_panel):
        """Test that summary() produces formatted output."""
        summary_str = python_rank_results_full_panel.summary()

        # Should contain key information
        assert "Panel Cointegration Rank Test" in summary_str
        assert "r = 0" in summary_str
        # Accept both singular and plural forms
        assert "Selected rank" in summary_str or "Selected Ranks" in summary_str

    def test_results_attributes(self, python_rank_results_full_panel):
        """Test that result object has expected attributes."""
        results = python_rank_results_full_panel

        # Should have selected rank
        assert hasattr(results, "selected_rank")
        assert isinstance(results.selected_rank, int)

        # Should have test details
        assert hasattr(results, "trace_tests")
        assert hasattr(results, "maxeig_tests")
        assert isinstance(results.trace_tests, list)
        assert isinstance(results.maxeig_tests, list)

        # Each test result should have required fields
        for test in results.trace_tests:
            assert hasattr(test, "rank")
            assert hasattr(test, "test_stat")
            assert hasattr(test, "p_value")


if __name__ == "__main__":
    # Run tests
    pytest.main([__file__, "-v", "-s"])
