"""
Validation tests for lag selection against R implementation.

This test suite compares PanelBox's lag selection with R's plm package
for information criteria calculation and lag order selection.
"""

import json
import subprocess
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from panelbox.var import PanelVAR, PanelVARData

pytestmark = pytest.mark.r_validation


@pytest.fixture(scope="module")
def r_lag_selection_results():
    """
    Run R lag selection script and return results.

    Returns
    -------
    dict
        Dictionary containing R lag selection results including:
        - ic_table: DataFrame with AIC, BIC, HQIC, MBIC for each lag
        - selected: dict of selected lags by criterion
        - true_lag: true lag order used to generate data
    """
    # Path to R script
    script_path = Path(__file__).parent / "test_vs_r_lag_selection.R"

    # Run R script
    result = subprocess.run(
        ["Rscript", str(script_path)], capture_output=True, text=True, timeout=120
    )

    if result.returncode != 0:
        pytest.skip(f"R script failed: {result.stderr}")

    # Load results
    results_path = Path("/tmp/pvar_lag_selection_results.json")
    if not results_path.exists():
        pytest.skip("R lag selection results file not found")

    with open(results_path) as f:
        r_results = json.load(f)

    return r_results


@pytest.fixture(scope="module")
def python_lag_selection_results(r_lag_selection_results):
    """
    Run lag selection using PanelBox with the same data as R.

    Parameters
    ----------
    r_lag_selection_results : dict
        R lag selection results (triggers R script execution)

    Returns
    -------
    LagOrderResult
        Lag selection results from PanelBox
    """
    # Load data generated by R
    data_path = Path("/tmp/pvar_lag_selection_data.csv")
    if not data_path.exists():
        pytest.skip("R lag selection data not found")

    df = pd.read_csv(data_path)

    # Create PanelVARData
    pvar_data = PanelVARData(
        data=df,
        endog_vars=["y1", "y2", "y3"],
        entity_col="entity",
        time_col="time",
        lags=1,  # Will be overridden by select_lag_order
        trend="none",
    )

    # Estimate with lag selection
    model = PanelVAR(pvar_data)
    max_lags = 6  # Same as R script
    lag_result = model.select_lag_order(max_lags=max_lags)

    return lag_result


class TestLagSelectionVsR:
    """Test suite for lag selection validation against R."""

    def test_aic_values_close(self, python_lag_selection_results, r_lag_selection_results):
        """
        Test that AIC values match R results within tolerance.
        """
        # Get Python AIC values from criteria_df
        df = python_lag_selection_results.criteria_df
        aic_py = df["AIC"].values

        # Get R AIC values (ic_table is a list of dicts)
        aic_r = [row["aic"] for row in r_lag_selection_results["ic_table"]]

        # Compare
        np.testing.assert_allclose(
            aic_py, aic_r, rtol=0.02, atol=0.02, err_msg="AIC values do not match R implementation"
        )

    def test_bic_values_close(self, python_lag_selection_results, r_lag_selection_results):
        """
        Test that BIC values match R results within tolerance.
        """
        # Get Python BIC values from criteria_df
        df = python_lag_selection_results.criteria_df
        bic_py = df["BIC"].values

        # Get R BIC values (ic_table is a list of dicts)
        bic_r = [row["bic"] for row in r_lag_selection_results["ic_table"]]

        # Compare
        np.testing.assert_allclose(
            bic_py, bic_r, rtol=0.02, atol=0.02, err_msg="BIC values do not match R implementation"
        )

    def test_hqic_values_close(self, python_lag_selection_results, r_lag_selection_results):
        """
        Test that HQIC values match R results within tolerance.
        """
        # Get Python HQIC values from criteria_df
        df = python_lag_selection_results.criteria_df
        hqic_py = df["HQIC"].values

        # Get R HQIC values (ic_table is a list of dicts)
        hqic_r = [row["hqic"] for row in r_lag_selection_results["ic_table"]]

        # Compare
        np.testing.assert_allclose(
            hqic_py,
            hqic_r,
            rtol=0.02,
            atol=0.02,
            err_msg="HQIC values do not match R implementation",
        )

    def test_mbic_values_close(self, python_lag_selection_results, r_lag_selection_results):
        """
        Test that MBIC values match R results within tolerance.
        """
        # Get Python MBIC values from criteria_df
        df = python_lag_selection_results.criteria_df
        mbic_py = df["MBIC"].values

        # Get R MBIC values (ic_table is a list of dicts)
        mbic_r = [row["mbic"] for row in r_lag_selection_results["ic_table"]]

        # Compare
        np.testing.assert_allclose(
            mbic_py,
            mbic_r,
            rtol=0.02,
            atol=0.02,
            err_msg="MBIC values do not match R implementation",
        )

    def test_selected_lags_match(self, python_lag_selection_results, r_lag_selection_results):
        """
        Test that selected lag orders match R for each criterion.

        Note: In some cases, due to numerical precision, the selected lag
        may differ by 1. We allow for this in the test.
        """
        # Get Python selected lags
        selected_py = python_lag_selection_results.selected

        # Get R selected lags
        selected_r = r_lag_selection_results["selected"]

        # Compare each criterion (allow difference of 1 due to numerical precision)
        for criterion in ["AIC", "BIC", "HQIC", "MBIC"]:
            lag_py = selected_py[criterion]
            lag_r = selected_r[criterion]

            assert abs(lag_py - lag_r) <= 1, (
                f"{criterion} selected lag mismatch: Python={lag_py}, R={lag_r}"
            )

    def test_bic_selects_true_lag(self, python_lag_selection_results, r_lag_selection_results):
        """
        Test that BIC selects the true lag order (2) or close to it.

        Note: In finite samples, BIC may not always select exactly the true lag.
        We test that both Python and R select the same lag and that it's close to 2.
        """
        true_lag = r_lag_selection_results["true_lag"]

        # Get selected lags
        bic_py = python_lag_selection_results.selected["BIC"]
        bic_r = r_lag_selection_results["selected"]["BIC"]

        # Both should select the same lag (or within 1)
        assert abs(bic_py - bic_r) <= 1, f"BIC selected lag mismatch: Python={bic_py}, R={bic_r}"

        # Selected lag should be close to true lag (within 1)
        assert abs(bic_py - true_lag) <= 1, (
            f"BIC did not select true lag: selected={bic_py}, true={true_lag}"
        )


if __name__ == "__main__":
    # Run tests
    pytest.main([__file__, "-v", "-s"])
